" Most of this is stolen from eatnumber ehouse and ryansb, with some stuff
" from spf13, Thanks!


set nocompatible
set rtp+=~/.vim/bundle/Vundle.vim

" Install plugins with vundle "
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'altercation/vim-colors-solarized'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/syntastic'
Plugin 'airblade/vim-gitgutter'
Plugin 'jnwhiteh/vim-golang'
Plugin 'tpope/vim-markdown'
Plugin 'bling/vim-airline'
Plugin 'jmcantrell/vim-virtualenv'
Plugin 'klen/python-mode'
Plugin 'wting/rust.vim'
Plugin 'guns/vim-clojure-static'
Plugin 'tpope/vim-fireplace.git'
Plugin 'kien/rainbow_parentheses.vim'
call vundle#end()

filetype indent plugin on
syntax on

set background=light
set hidden
set wildmenu
set showcmd
set hlsearch
set incsearch

set ignorecase
set smartcase

set backspace=indent,eol,start
set autoindent
set nostartofline
set ruler

set laststatus=2
set confirm
set visualbell
set t_vb=
set mouse=a
set cmdheight=2
set number
set notimeout ttimeout ttimeoutlen=200

set shiftwidth=4
set softtabstop=4
set expandtab

map Y y$
nnoremap <C-L> :nohl<CR><C-L>


let g:syntastic_c_compiler = "clang"
let g:syntastic_cpp_compiler = "clang++"

set listchars=nbsp:.,eol:$,tab:>-,trail:~,extends:>,precedes:<
set list
hi NonText guifg=#262626 ctermfg=236
hi SpecialKey guifg=#262626 ctermfg=236

inoremap jj <ESC>

set scrolloff=5 "Keep the cursor at least 5 lines from the top and bottom
set scrolljump=0 "Keep the cursor at least 5 lines from the top and bottom

" Yank to system clipboard


map <Leader>y "+y

highlight clear SignColumn " SignColumn should match background
highlight clear LineNr " Current line number row will have same background color in relative mode
let g:CSApprox_hook_post = ['hi clear SignColumn']
"highlight clear CursorLineNr " Remove highlight color from current
"line number
"if has('statusline')
"        set laststatus=2
"        " Broken down into easily includeable segments
"        set statusline=%<%f\ " Filename
"        set statusline+=%w%h%m%r " Options
"        set statusline+=%{fugitive#statusline()} " Git Hotness
"        set statusline+=\ [%{&ff}/%Y] " Filetype
"        set statusline+=\ [%{getcwd()}] " Current dir
"        set statusline+=%=%-14.(%l,%c%V%)\ %p%% " Right aligned file nav info
"endif

cmap w!! w !sudo tee % >/dev/null
nnoremap <silent> <leader>tt :TagbarToggle<CR>

"Disable pymodes rope scripts
let g:pymode_rope = 0

au BufNewFile,BufRead *.rs set filetype=rust
au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces
set colorcolumn=80
