export TERM=xterm-256color

ZSH=$HOME/.zsh

# Always use menu completion, and make the colors pretty!
zstyle ':completion:*' menu select yes
zstyle ':completion:*:default' list-colors ''

autoload -Uz compinit
compinit
autoload -U colors && colors
autoload -U add-zsh-hook

source $ZSH/git.zsh
source $ZSH/dstufft.zsh


bindkey -e
setopt append_history
setopt extended_history     # save each command's beginning timestamp and the duration to the history file
setopt inc_append_history
setopt share_history
setopt histignorespace      # remove command lines from the history list when
setopt auto_cd              # if a command is issued that can't be executed as a normal command,
setopt extended_glob        # in order to use #, ~ and ^ for filename generation
setopt longlistjobs         # display PID when suspending processes as well
setopt notify               # report the status of backgrounds jobs immediately
setopt hash_list_all        # Whenever a command completion is attempted, make sure \
setopt completeinword       # not just at the end
setopt nohup                # and don't kill them, either
setopt auto_pushd           # make cd push the old directory onto the directory stack.
setopt nonomatch            # try to avoid the 'zsh: no matches found...'
setopt nobeep               # avoid "beep"ing
setopt pushd_ignore_dups    # don't push the same dir twice.
setopt noglobdots           # * shouldn't match dotfiles. ever.
setopt noshwordsplit        # use zsh style word splitting
setopt unset                # don't error out when unset parameters are used

export HISTFILE=$HOME/.zhistory
export HISTSIZE=100000
export SAVEHIST=100000

source $HOME/.cargo/env
export WORKON_HOME=$HOME/.virtualenvs
export EDITOR="vim"
export GOPATH=$HOME/src/repos/server/go
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:/usr/local/opt/go/libexec/bin
export PATH=$PATH:$HOME/bin

alias s="ssh"
alias rsync="rsync -h --progress"
alias irc="ssh -t losna 'screen -dx'"


# simple webserver
function server() {
    local port="${1:-8000}"
    open "http://localhost:${port}/"
    python -m SimpleHTTPServer "$port"
}
